using System;
using System.Collections.Generic;
using Bridge.NET.Test.Helpers;
using Bridge.React;

// Content generated by React Bindings Maker
namespace FluentReact
{
	public sealed partial class DomBuilder
	{
		private readonly List<object> list = new Fluent.FluentList<object>();
		private int elIndex = 1;
		private int elRangeIndex = -1;



		private DomBuilder AddElement(TagName tagName, Attributes propSetter, ReactElement child)
		{
			throw new NotImplementedException();
		}

		private DomBuilder AddElement(TagName tagName, Attributes propSetter, IEnumerable<ReactElement> children)
		{
			throw new NotImplementedException();
		}

		public enum TagName 
		{
			Div
		}
	}

	public sealed partial class DomBuilderDynamicChildren
	{

	}

	public sealed partial class DomBuilder
	{

		public DomBuilder Abbr(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Address(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Area(Action<AreaAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Article(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Aside(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Audio(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder B(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Base(Action<BaseAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder BDI(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder BDO(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Big(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder BlockQuote(Action<QuoteAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Body(Action<BodyAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Br(Action<BrAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Button(Action<ButtonAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Canvas(Action<CanvasAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Caption(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Cite(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Code(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Col(Action<TableColAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder ColGroup(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Data(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder DataList(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder DD(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Del(Action<DelAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Details(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Dfn(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Dialog(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Div(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder DL(Action<DListAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder DT(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Em(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Embed(Action<EmbedAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder FieldSet(Action<FieldSetAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder FigCaption(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Figure(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Footer(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Form(Action<FormAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder H1(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder H2(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder H3(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder H4(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder H5(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder H6(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Head(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Header(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder HGroup(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Hr(Action<HRAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Html(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder I(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder IFrame(Action<IFrameAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Img(Action<ImageAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Input(Action<InputAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Ins(Action<InsAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Kbd(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Keygen(Action<KeygenAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Label(Action<LabelAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Legend(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Li(Action<LIAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Link(Action<LinkAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Main(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Map(Action<MapAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Mark(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Menu(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder MenuItem(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Meta(Action<MetaAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Meter(Action<MeterAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Nav(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder NoScript(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Object(Action<ObjectAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder OL(Action<OListAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder OptGroup(Action<OptGroupAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Option(Action<OptionAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Output(Action<OutputAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder P(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Param(Action<ParamAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Picture(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Pre(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Progress(Action<ProgressAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Q(Action<QuoteAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder RP(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder RT(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Ruby(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder S(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Samp(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Script(Action<ScriptAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Section(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Select(Action<SelectAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Small(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Source(Action<SourceAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Span(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Strong(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Style(Action<StyleAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Sub(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Summary(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Sup(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Table(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder TBody(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder TD(Action<TableCellAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder TextArea(Action<TextAreaAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder TFoot(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder TH(Action<TableCellAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder THead(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Time(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Title(Action<TitleAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder TR(Action<TableCellAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Track(Action<TrackAttributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder U(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder UL(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Var(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder Video(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
        public DomBuilder WBR(Action<Attributes> propSetter, DomBuilder children = null)
            => AddElements(propSetter, children);
        
    }
    
}
